version: "3.7"

services:
  seed:
    image: prologic/bitraft
    entrypoint:
      - timeout # this seed fires up the cluster after which it is no longer needed
      - -sTERM  # this is the same signal as docker would send on a scale down / stop
      - -t30    # terminate after 30 seconds
    command:
      - /bitraft
      - -d=/tmp/bitraft
      - -b={{ GetInterfaceIP "eth0" }}:4920
    networks:
      - bitraft
    deploy:
      restart_policy:
        condition: none
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"

  cluster:
    image: prologic/bitraft
    command:
      - -d=/data
      - -j=seed:4920
      - -b={{ GetInterfaceIP "eth0" }}:4920
    networks:
      - bitraft
    deploy:
      mode: global                                      ##this will deploy to all nodes that

networks:
  bitraft:
    driver: overlay
    name: bitraft
    attachable: true
